// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSite1.Models;

namespace WebSite1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210110201721_testmig2")]
    partial class testmig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebSite1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Face"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Eyes"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Brows"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Lips"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Brushes"
                        });
                });

            modelBuilder.Entity("WebSite1.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 1,
                            Description = "Though this is technically a primer, I use it as a light-coverage foundation, and it gives the most candle-lit, non-cakey glow you can possibly imagine.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074696-best-makeup-0013-charlotte-tilbury-wonderglow-40ml-0-1499864840-main-1529074664.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074696-best-makeup-0013-charlotte-tilbury-wonderglow-40ml-0-1499864840-main-1529074664.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Charlotte Tilbury Wonderglow Primer",
                            Price = 55.0
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 2,
                            Description = "Milk Makeup",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560971011-s2117976-main-zoom.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560971011-s2117976-main-zoom.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Blur + Set Matte Loose Setting Powder by Milk Makeup",
                            Price = 29.0
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 3,
                            Description = "This tiny but powerful tool fills in your brows with the most natural - looking finish.Its super skinny pencil mimics actual individual hairs, and the smudge - proof formula sticks on even without using a gel on top.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078075-best-makeup-0005-browwiz-1529078066.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078075-best-makeup-0005-browwiz-1529078066.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Anastasia Beverly Hills Brow Wiz",
                            Price = 23.0
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 2,
                            Description = "This palette is the holy grail: 12 different shades that work well together to build eye looks that range from simple to sultry depending on how they’re used together. It’s currently limited edition, but I’ll be gutted if it ever leaves!",
                            ImageThumbnailUrl = "https://www.keemia.ee/sites/default/files/styles/page_large/public/2018-04/DDIFFERENCE-Natural-Beauty_group_web_0.jpg?itok=ycw_yg07",
                            ImageUrl = "https://www.keemia.ee/sites/default/files/styles/page_large/public/2018-04/DDIFFERENCE-Natural-Beauty_group_web_0.jpg?itok=ycw_yg07",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Skin Deep Eye Palette by NARS",
                            Price = 59.0
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 4,
                            Description = "Look, it’s just that good. This “lip gel” has a nice glossy finish without feeling sticky and has the perfect amount of pink tint to enhance the natural color of my lip without giving me that ashy pink look. You know the ashy pink look I’m talking about.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970921-screen-shot-2019-06-19-at-3-01-42-pm-1560970914.png?crop=0.7240915208613729xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970921-screen-shot-2019-06-19-at-3-01-42-pm-1560970914.png?crop=0.7240915208613729xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Ultra Shine Lip Gel",
                            Price = 12.0
                        },
                        new
                        {
                            ItemId = 7,
                            CategoryId = 4,
                            Description = "Carmex lip balm was introduced to me as a child (thanks mom!) and it's been my go-to ever since. No matter dry my lips are, this treatment hydrates and softens skin immediately.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560976628-13048468.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560976628-13048468.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Carmex Classic Medicated Lip Balm Tube",
                            Price = 2.77
                        },
                        new
                        {
                            ItemId = 8,
                            CategoryId = 2,
                            Description = "Benefit’s They’re Real has always performed like a champ. It gives my barely visible lashes the extra oomph they need and, most importantly, stays put!",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560971580-they-rereal-1560971569.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560971580-they-rereal-1560971569.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "They're Real! Lengthening Mascara by Benefit Cosmetics",
                            Price = 24.0
                        },
                        new
                        {
                            ItemId = 9,
                            CategoryId = 4,
                            Description = "The formula goes on smoothly (not sticky) and smells wonderfully. The All that Glitters shade amps up my natural lip tone without making them over the top!",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560961038-Lipgloss_Coming_Up_Rose_1024x1024.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560961038-Lipgloss_Coming_Up_Rose_1024x1024.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Perfect Shine Hydrating Lip Gloss",
                            Price = 12.0
                        },
                        new
                        {
                            ItemId = 10,
                            CategoryId = 2,
                            Description = "Precision, pigment, and long-lasting results. That's what you get with Kat Von D's cult-favorite Tattoo Liner. You'll never have to do retouches or worry about smudges.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078156-best-makeup-0003-katvondliner-1529078146.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078156-best-makeup-0003-katvondliner-1529078146.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Kat Von D Tattoo Liner",
                            Price = 21.0
                        },
                        new
                        {
                            ItemId = 11,
                            CategoryId = 2,
                            Description = "It's the perfect balance of light sheer coverage that can quickly transform into a full face beat. Beyond the versatility of the product, it's packed with goji berry (an antioxidant that does wonders for the skin!) and SPF 30. This product is the Michael Jordan of beauty; it's the GOAT.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075460-best-makeup-0010-fabskintint-1529075453.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075460-best-makeup-0010-fabskintint-1529075453.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "First Aid Beauty Hello FAB Triple Protection Skin Tint with Goji Berry SPF 30",
                            Price = 34.0
                        },
                        new
                        {
                            ItemId = 12,
                            CategoryId = 1,
                            Description = "Flesh Firm Flesh stick foundations mix and match and go on with such ease",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560961223-flesh-1560961213.jpg?crop=0.9989827060020345xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560961223-flesh-1560961213.jpg?crop=0.9989827060020345xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Soft, flattering foundation with a dewy finish by flesh beauty",
                            Price = 18.0
                        },
                        new
                        {
                            ItemId = 13,
                            CategoryId = 2,
                            Description = "Of all the drugstore and high-end eyeliners I’ve glided across my eyes, none comes close to the love I have for L’Oreal’s Infallible Super Slim. The rich pigment, ultra-fine tip, the easy application, and matte black finish—I have no choice but to stan!",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970423-14306432.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970423-14306432.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "L'Oreal Paris Cosmetics Infallible Super Slim Liquid Eyeliner",
                            Price = 7.3899999999999997
                        },
                        new
                        {
                            ItemId = 14,
                            CategoryId = 2,
                            Description = "Charlotte Tilbury's shades are work-appropriate but can be amped up for any after-work hangouts. Plus, the bronzer and blush shades double as extra eyeshadow colors.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560976777-charlotte-tilbury-face-palettes-instant-look-in-a-palette-beauty-glow.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560976777-charlotte-tilbury-face-palettes-instant-look-in-a-palette-beauty-glow.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Instant Look in a Palette by Charlotte Tilbury",
                            Price = 75.0
                        },
                        new
                        {
                            ItemId = 15,
                            CategoryId = 2,
                            Description = "As far as drugstore mascaras go it doesn't get any better than Lash Paradise. It lengthens, separates, never clumps, and holds a curl all while coming in under $10. Buy in bulk.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078183-best-makeup-0002-lorealparishvolumelash-1529078173.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078183-best-makeup-0002-lorealparishvolumelash-1529078173.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "L'Oreal Paris Voluminous Lash Paradise Waterproof Mascara",
                            Price = 9.9700000000000006
                        },
                        new
                        {
                            ItemId = 16,
                            CategoryId = 1,
                            Description = "If you want to frost yourself in the most tried and true way, the tiny light-reflective particles of this classic highlighter stick will support that mission. It will never let you down, either; I got complimented on its very glowy but subtle effects just this week.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075262-best-makeup-0005-narsorgasm-1529075250.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075262-best-makeup-0005-narsorgasm-1529075250.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "NARS The Multiple",
                            Price = 39.0
                        },
                        new
                        {
                            ItemId = 17,
                            CategoryId = 1,
                            Description = "Powder highlighters tend to sit on the surface of my skin but Lancome’s liquid gold seeps into my skin to give me a lit-from-within glow.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970587-3614271973788_CustomGlowDrops_BronzeGlow.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970587-3614271973788_CustomGlowDrops_BronzeGlow.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Teint Idole Ultra Custom Highlighting Drops",
                            Price = 35.0
                        },
                        new
                        {
                            ItemId = 18,
                            CategoryId = 2,
                            Description = "On the days I don't feel like wearing makeup, this miracle mascara always makes my lashes pop. While the lipstick colors and eye palettes change, it's a steady standby in my beauty arsenal.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074830-best-makeup-0002-toofacedbetterthansex-1529074822.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074830-best-makeup-0002-toofacedbetterthansex-1529074822.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Too Faced Better Than Sex Mascara",
                            Price = 26.0
                        },
                        new
                        {
                            ItemId = 19,
                            CategoryId = 1,
                            Description = "I love this smoothing primer. It totally minimizes the appearance of all my pores, and doesn’t feel heavy on my face. Plus, a little goes a longggg way. One tiny tube lasted me for almost an entire year.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560974687-porefessional-1560974682.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560974687-porefessional-1560974682.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "The POREfessional Face Primer",
                            Price = 31.0
                        },
                        new
                        {
                            ItemId = 20,
                            CategoryId = 1,
                            Description = "If dewy, your-skin-but-better is what you seek, look no further than this heavenly cushion compact from La Prairie. It has buildable, light-to-medium coverage that evens out skin tone, acts like a treatment thanks to its built-in essence, and magically feels like nothing on your face. I've never seen a foundation with such an undetectable finish (most foundations look/feel like masks), and though pricy, this formula can't be beat.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078130-best-makeup-0000-skincaviarlaprairie-1529078121.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078130-best-makeup-0000-skincaviarlaprairie-1529078121.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "La Prairie Essence-In Foundation",
                            Price = 210.0
                        },
                        new
                        {
                            ItemId = 21,
                            CategoryId = 2,
                            Description = "Can't! Live! Without! Vaseline! Makeup remover? Check. A lil balm for chapped lips? Check. A dry cuticle? CHECK. Vaseline is my desert island beauty supply. Vas or die.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074752-best-makeup-0000-vaseline-1529074737.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074752-best-makeup-0000-vaseline-1529074737.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Vaseline Petroleum Jelly Original",
                            Price = 4.1900000000000004
                        },
                        new
                        {
                            ItemId = 22,
                            CategoryId = 5,
                            Description = "Morphe’s M439 Brush is a classic. I use this brush to apply my liquid foundation and it blends the product out like a dream so no signs of streaks or patches, just a flawless mug.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970675-morphe-1560970670.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560970675-morphe-1560970670.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "M439 Deluxe Buffer Brush",
                            Price = 14.0
                        },
                        new
                        {
                            ItemId = 23,
                            CategoryId = 4,
                            Description = "I believe a bright, bold red lip is appropriate no matter the occasion: Work, home, dinner, parties, gym (yes, the gym!). This Maybelline lipstick in endless raisin is my go-to color. It slides on easy, doesn’t smudge, and lasts all.day.long.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560974527-maybelline-1560974523.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560974527-maybelline-1560974523.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Superstay 14 Hour Lipstick, Endless Raisin",
                            Price = 12.0
                        },
                        new
                        {
                            ItemId = 24,
                            CategoryId = 4,
                            Description = "Every beauty bag needs a tinted lip balm for days you don't want to worry about a lipstick, but don't want naked lips. Dior's Lip Glow (a Bella Hadid favorite) is the ultimate, ultimate formula. Its ultra nourishing and adaptable: You can go light with the tint or layer for stronger color payoff. Plus, you don't need a mirror to apply.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078203-best-makeup-0004-dior-1529078192.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078203-best-makeup-0004-dior-1529078192.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Dior Addict Lip Glow Color Reviver Balm",
                            Price = 34.0
                        },
                        new
                        {
                            ItemId = 25,
                            CategoryId = 1,
                            Description = "I cannot sing MAKE's praises enough. My latest MAKE obsession is its Bronzing Brick. I switch between the Joshua Tree and Marfa shades, depending on how glorious my tan is on any given day. It offers a light contour that works for everyday, and, best of all its vegan, fragrance-free formula never irritates my sensitive skin.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074916-best-makeup-0007-makebronzingbrick-1529074904.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074916-best-makeup-0007-makebronzingbrick-1529074904.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "MAKE Bronzing Bricks",
                            Price = 12.0
                        },
                        new
                        {
                            ItemId = 26,
                            CategoryId = 2,
                            Description = "A makeup artist friend recommended this lengthening mascara to me few years ago, and I’ve been using it ever since! I like having long dramatic lashes and this delivers. It stays on at the gym, but washes off easily at home, which is definitely a plus.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560974123-31XkwMUYdhL.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1560974123-31XkwMUYdhL.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "L'Oréal Paris Makeup Telescopic Original Lengthening Mascara, Carbon Black",
                            Price = 8.4399999999999995
                        },
                        new
                        {
                            ItemId = 27,
                            CategoryId = 1,
                            Description = "I never was a foundation girl. I always deemed a base—especially full-coverage—too much of a mask atop my skin and my nine step care routine. I never knew how incomplete I looked, though, with a full face of makeup (brows, eyes, cheeks, highlight) on bare skin. But when I discovered Becca's full coverage formula, I fell in love. Although it's full coverage, when wearing it, I just look like I have amazing skin. My secret: apply a pea-sized amount on a damp foundation brush and massage all over my face. A little bit goes a long way, evens out my tone and texture, and makes for the perfect base for the rest of my kit.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529067090-s2076172-main-zoom.jpg?crop=0.667xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529067090-s2076172-main-zoom.jpg?crop=0.667xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "BECCA Ultimate Coverage 24-Hour Foundation",
                            Price = 44.0
                        },
                        new
                        {
                            ItemId = 28,
                            CategoryId = 2,
                            Description = "For a long time I was shelling out $34 for a YSL eyeliner that I swore was the best, but that was before I discovered Eyeko's $22 version. It's $12 cheaper, and has twice the staying power.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529066968-_102552863.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529066968-_102552863.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Skinny Mini Liquid Black Eyeliner",
                            Price = 12.0
                        },
                        new
                        {
                            ItemId = 29,
                            CategoryId = 1,
                            Description = "Honest Beauty's Cream Blush is a new addition to my beauty arsenal. I've gotten so many compliments that I threw out my old blush. It's creamy, soft, and shimmery. Meghan Markle is also rumored to have worn this blush during her wedding to Prince Harry. Need I say more?",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075520-best-makeup-0008-honestbeautyblush-1529075512.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075520-best-makeup-0008-honestbeautyblush-1529075512.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Honest Beauty Cream Blush",
                            Price = 22.0
                        },
                        new
                        {
                            ItemId = 30,
                            CategoryId = 2,
                            Description = "Every single time I wear this mascara around our former ELLE writer Mattie Kahn asks, 'Oh my GOD are your lashes FAKE or just super long?' Reader, they are not, I'm just wearing this amazingly underrated product.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074803-best-makeup-0011-eyekolashalert-1529074781.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074803-best-makeup-0011-eyekolashalert-1529074781.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Eyeko Online Only Lash Alert Mascara",
                            Price = 26.0
                        },
                        new
                        {
                            ItemId = 31,
                            CategoryId = 3,
                            Description = "Who would've thought QVC would be the brow bearer of my dreams? My makeup artist friend gifted me this precious little pot and not a single pencil from my past can compare. I always do my brows first, and use an angled brush to apply where my brow fullness falls short. Although it's a waxy formula, it settles like a powder—and doesn't require a setting powder or mist to stay in place all day.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075154-best-makeup-0009-fionastilesbrow-1529074967.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075154-best-makeup-0009-fionastilesbrow-1529074967.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Fiona Stiles Brow Sculpting Wax",
                            Price = 22.0
                        },
                        new
                        {
                            ItemId = 32,
                            CategoryId = 4,
                            Description = "This product lives somewhere in the blissful, mythical space between a lipstick and lipgloss. It is the EXACT color of my lips and so it really just enhances what I already have in a pretty, natural way. Without a doubt the best lipstick I've ever used.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075296-best-makeup-0014-chanelrouse-1529075289.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075296-best-makeup-0014-chanelrouse-1529075289.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Chanel Rouge Hydrating Lip Colour",
                            Price = 40.0
                        },
                        new
                        {
                            ItemId = 33,
                            CategoryId = 4,
                            Description = "Ruby Woo is the ultimate red matte lip and anyone who says otherwise just doesn't want you to sell this out. The evil geniuses at M.A.C. crafted this color years ago and whenever I want the ultimate sultry shade, I reach for my girl Ruby Woo. It's not drying and lasts all day long. She's perfect.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074650-best-makeup-0004-rubyroomac-1529074641.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529074650-best-makeup-0004-rubyroomac-1529074641.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "M.A.C. Red Lipstick in Ruby Woo",
                            Price = 15.73
                        },
                        new
                        {
                            ItemId = 34,
                            CategoryId = 2,
                            Description = "This is the only makeup item I'm genuinely excited to repeat buy. With a truly tenacious formula, an applicator that's firm enough for a smooth line yet flexible enough for those all-important cat-eye flicks, this Stila savior has come home with me over and over again.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075183-best-makeup-0003-stilawaterproof-1529075172.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075183-best-makeup-0003-stilawaterproof-1529075172.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Stila Stay All Day Waterproof Liquid Eye Liner",
                            Price = 22.0
                        },
                        new
                        {
                            ItemId = 35,
                            CategoryId = 1,
                            Description = "My skin tends to be oily and redness prone, so this easy powder is my go-to. It provides light coverage but makes my complexion look that much smoother.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075572-best-make-up-1529068595-s1848134-main-zoom-1529075560.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075572-best-make-up-1529068595-s1848134-main-zoom-1529075560.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Bare Minerals BarePro Performance Wear Powder Foundation",
                            Price = 31.0
                        },
                        new
                        {
                            ItemId = 36,
                            CategoryId = 1,
                            Description = "This is, hands down, the best setting powder. Aside from smelling like summer, the powder has a unique design that ensures you don't get loose powder all over your vanity and clothes, but rather only along your your T-Zone to mattify.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078103-best-makeup-0001-marcjacobscoconutsetting-1529078090.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529078103-best-makeup-0001-marcjacobscoconutsetting-1529078090.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "Marc Jacobs Perfecting Coconut Setting Powder",
                            Price = 44.0
                        },
                        new
                        {
                            ItemId = 37,
                            CategoryId = 1,
                            Description = "This is the first high-end beauty product I ever bought, so it holds a special place in my heart. The color is eye-catching, but I still love to wear it for a casual day if I'm feeling fancy.",
                            ImageThumbnailUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075617-best-makeup-1529069024-s1495274-main-zoom-1529075587.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            ImageUrl = "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1529075617-best-makeup-1529069024-s1495274-main-zoom-1529075587.jpg?crop=1xw:1xh;center,top&resize=768:*",
                            IsInStock = true,
                            IsOnSale = true,
                            Name = "NARS Lipstick",
                            Price = 35.0
                        });
                });

            modelBuilder.Entity("WebSite1.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebSite1.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebSite1.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebSite1.Models.Item", b =>
                {
                    b.HasOne("WebSite1.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebSite1.Models.OrderDetail", b =>
                {
                    b.HasOne("WebSite1.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebSite1.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebSite1.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("WebSite1.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebSite1.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebSite1.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
